name: armor-unet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pillow
  - matplotlib
  - pip:
      - --pre
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu128
      - torch
      - torchvision
      - pytorch-lightning>=2.2
      - albumentations>=1.3
      - wandb>=0.16
      - roboflow
      - ray[tune]